[project]
name = "spekk"
version = "2.0.0"
description = "Python Array API with named dimensions"
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "Magnus Dalen Kvalevåg", email = "magnus.kvalevag@ntnu.no" },
]
dependencies = [
    "array-api-compat>=1.12.0",
    "numpy>=2.2.6",
    "typing-extensions>=4.14.0",
]

[dependency-groups]
dev = [
    "hypothesis>=6.130.5",
    "ipykernel>=6.29.5",
    "jax>=0.6.1",
    "ndindex>=1.8",
    "pyright",
    "pytest",
    "pytest-cov>=6.2.1",
    "pytest-json-report>=1.5.0",
    "pytest-xdist>=3.7.0",
    "ruff>=0.11.12",
    "spekk",
]

[tool.uv.sources]
spekk = { workspace = true }


[build-system]
requires = ["hatchling>=1.10.0"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["spekk", "spekk.*"]
